services:
  postgres:
    ports:
      - 5432:5432
    container_name: postgres-cont
    image: postgres
    environment:
      - POSTGRES_DB=springstore_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /d/postgres_docker_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springstore-cont
    ports:
      - 8081:8081
    environment:
#      db-url: jdbc:postgresql://postgres:5432/springstore_db
#      db-username: postgres
#      db-password: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springstore_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: always