name: Build Docker Image for Spring Store

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: springstore_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Verify Java version
        run: |
          java --version
          echo "JAVA_HOME: $JAVA_HOME"
          which java

      - name: Verify Maven version
        run: mvn -v

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Build Docker image
        run: docker build -t springstore:latest .

      - name: Test Docker image
        run: |
          docker run --rm -d \
            --name springstore-test \
            --network host \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/springstore_db \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=postgres \
            springstore:latest
          
#           Wait a bit for the app to start
          sleep 30
          
          # Check if container is still running
          docker ps | grep springstore-test || echo "Container stopped"
          
          # Stop the test container
          docker stop springstore-test || true