name: Build Docker Image for Spring Store

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: springstore_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: sudo ./mvnw -B clean package -D skiptest

      - name: Build Docker image
        run: docker build -t springstore:latest .

      - name: Run Docker image (test it)
        run: |
          docker run --rm \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/springstore_db \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=postgres \
            springstore:latest

      # Optional: Push to DockerHub / GHCR
      # - name: Login to Docker Hub
      #   run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # - name: Push image
      #   run: docker tag springstore yourname/springstore:latest && docker push yourname/springstore:latest
